#!/usr/bin/env python3
"""Generate the bounded, checked-in word list used by glide.c."""

import gzip
import hashlib
import os
import re
import sys

COMPRESSED_SIZE = 538_593
COMPRESSED_SHA256 = "5b3c6c418fea7188b3919c47829ff94bc010f8336c74cbb929cc20d0c9d9e901"
NORMALIZED_SHA256 = "563636f8dd43cebd00f7253298e1ef0032f830fcbe458dc6115f602fb543456c"
MAX_WORDS = 20_000
MAX_WORD_LENGTH = 24
MAX_BUCKET = 512
STATIC_PAYLOAD_LIMIT = 256 * 1024
BUCKET_TABLE_BYTES = 26 * 26 * 8
WORD = re.compile(rb"^[a-z][a-z]+$")


def fail(message):
    raise SystemExit("generate-glide-dictionary: " + message)


def main():
    if len(sys.argv) != 3:
        fail("usage: generate-glide-dictionary.py SOURCE.gz OUTPUT.h")
    source, output = sys.argv[1:]
    with open(source, "rb") as source_file:
        if os.fstat(source_file.fileno()).st_size != COMPRESSED_SIZE:
            fail("wrong compressed size")
        compressed = source_file.read(COMPRESSED_SIZE + 1)
        if len(compressed) != COMPRESSED_SIZE or source_file.read(1):
            fail("wrong compressed size")
    if hashlib.sha256(compressed).hexdigest() != COMPRESSED_SHA256:
        fail("wrong compressed hash")
    text = gzip.decompress(compressed)
    words = []
    seen = set()
    for line in text.splitlines():
        if len(line) <= MAX_WORD_LENGTH and WORD.fullmatch(line) and line not in seen:
            seen.add(line)
            words.append(line)
            if len(words) == MAX_WORDS:
                break
    normalized = b"\n".join(words) + b"\n"
    if len(words) != MAX_WORDS:
        fail("not enough normalized words")
    if hashlib.sha256(normalized).hexdigest() != NORMALIZED_SHA256:
        fail("wrong normalized hash")
    buckets = [[[] for _ in range(26)] for _ in range(26)]
    for word in words:
        bucket = buckets[word[0] - ord("a")][word[-1] - ord("a")]
        if len(bucket) < MAX_BUCKET:
            bucket.append(word)
    largest_count, largest_first, largest_last = max(
        (len(bucket), first, last)
        for first, row in enumerate(buckets)
        for last, bucket in enumerate(row)
    )
    retained = []
    ranges = []
    byte_position = 0
    for row in buckets:
        for bucket in row:
            ranges.append((len(bucket), byte_position))
            retained.extend(bucket)
            byte_position += sum(len(word) + 1 for word in bucket)
    payload = b"".join(word + b"\0" for word in retained)
    # Adjacent C string literals add one final implicit NUL beyond the explicit
    # per-word terminators in payload.
    static_payload = len(payload) + 1 + BUCKET_TABLE_BYTES
    if static_payload > STATIC_PAYLOAD_LIMIT:
        fail("dictionary payload is too large")
    with open(output, "w", encoding="ascii", newline="\n") as generated:
        generated.write("/* Generated by tools/generate-glide-dictionary.py. */\n")
        generated.write("#ifndef GLIDE_WORDS_EN_H\n#define GLIDE_WORDS_EN_H\n\n")
        generated.write("#define GLIDE_LARGEST_BUCKET_FIRST '%s'\n" % chr(ord("a") + largest_first))
        generated.write("#define GLIDE_LARGEST_BUCKET_LAST '%s'\n" % chr(ord("a") + largest_last))
        generated.write("#define GLIDE_LARGEST_BUCKET_COUNT %d\n" % largest_count)
        generated.write("static const unsigned char glide_word_bytes[] =\n")
        for word in retained:
            generated.write('    "' + word.decode("ascii") + '\\0"\n')
        generated.write("    ;\n")
        generated.write("struct glide_bucket_range { unsigned short count; unsigned int byte_start; };\n")
        generated.write("static const struct glide_bucket_range glide_buckets[26][26] = {\n")
        for row in range(26):
            generated.write("    {")
            generated.write(", ".join("{%d, %d}" % item for item in ranges[row * 26:(row + 1) * 26]))
            generated.write("},\n")
        generated.write("};\n\n#endif\n")


if __name__ == "__main__":
    main()
