#!/usr/bin/env python3
"""Generate the bounded, checked-in FrequencyWords list used by glide.c."""

import hashlib
import os
import re
import sys

SOURCE_SIZE = 622_749
SOURCE_SHA256 = "5351ff405b1126ef555791dd4d9798a48e3e9a501a9fc481a9da957752cfb458"
MAX_WORDS = 20_000
MAX_WORD_LENGTH = 24
MAX_BUCKET = 512
STATIC_PAYLOAD_LIMIT = 256 * 1024
BUCKET_TABLE_BYTES = 26 * 26 * 12
WORD = re.compile(rb"^[a-z][a-z]+$")


def fail(message):
    raise SystemExit("generate-glide-dictionary: " + message)


def generate(text, output):
    words = []
    seen = set()
    previous_count = None
    for line in text.splitlines():
        fields = line.split()
        if len(fields) != 2 or not fields[1].isdigit():
            fail("malformed frequency record")
        word, raw_count = fields
        count = int(raw_count)
        if count <= 0 or (previous_count is not None and count > previous_count):
            fail("frequency records are not positive and non-increasing")
        previous_count = count
        if (len(words) < MAX_WORDS and len(word) <= MAX_WORD_LENGTH and
                WORD.fullmatch(word) and word not in seen):
            seen.add(word)
            words.append(word)
    if len(words) != MAX_WORDS:
        fail("not enough normalized words")

    buckets = [[[] for _ in range(26)] for _ in range(26)]
    for word in words:
        bucket = buckets[word[0] - ord("a")][word[-1] - ord("a")]
        if len(bucket) == MAX_BUCKET:
            fail("dictionary bucket exceeds its bound")
        bucket.append(word)
    largest_count, largest_first, largest_last = max(
        (len(bucket), first, last)
        for first, row in enumerate(buckets)
        for last, bucket in enumerate(row)
    )
    retained = []
    ranges = []
    byte_position = 0
    for row in buckets:
        for bucket in row:
            byte_end = byte_position + sum(len(word) + 1 for word in bucket)
            ranges.append((len(bucket), byte_position, byte_end))
            retained.extend(bucket)
            byte_position = byte_end
    payload = b"".join(word + b"\0" for word in retained)
    # Adjacent C string literals add one final implicit NUL beyond the explicit
    # per-word terminators in payload.
    static_payload = len(payload) + 1 + BUCKET_TABLE_BYTES
    if static_payload > STATIC_PAYLOAD_LIMIT:
        fail("dictionary payload is too large")
    with open(output, "w", encoding="ascii", newline="\n") as generated:
        generated.write("/* Generated by tools/generate-glide-dictionary.py.\n")
        generated.write(" * Source: hermitdave/FrequencyWords content/2018/en/en_50k.txt\n")
        generated.write(" * Revision: 525f9b560de45753a5ea01069454e72e9aa541c6\n")
        generated.write(" * Content license: CC BY-SA 4.0; see THIRD_PARTY_LICENSES.md.\n")
        generated.write(" */\n")
        generated.write("#ifndef GLIDE_WORDS_EN_H\n#define GLIDE_WORDS_EN_H\n\n")
        generated.write("#define GLIDE_DICTIONARY_SHA256 \"" + SOURCE_SHA256 + "\"\n")
        generated.write("#define GLIDE_LARGEST_BUCKET_FIRST '%s'\n" % chr(ord("a") + largest_first))
        generated.write("#define GLIDE_LARGEST_BUCKET_LAST '%s'\n" % chr(ord("a") + largest_last))
        generated.write("#define GLIDE_LARGEST_BUCKET_COUNT %d\n" % largest_count)
        generated.write("static const unsigned char glide_word_bytes[] =\n")
        for word in retained:
            generated.write('    "' + word.decode("ascii") + '\\0"\n')
        generated.write("    ;\n")
        generated.write("struct glide_bucket_range { unsigned short count; unsigned int byte_start; unsigned int byte_end; };\n")
        generated.write("static const struct glide_bucket_range glide_buckets[26][26] = {\n")
        for row in range(26):
            generated.write("    {")
            generated.write(", ".join("{%d, %d, %d}" % item for item in ranges[row * 26:(row + 1) * 26]))
            generated.write("},\n")
        generated.write("};\n\n#endif\n")


def main():
    if len(sys.argv) != 3:
        fail("usage: generate-glide-dictionary.py en_50k.txt OUTPUT.h")
    source, output = sys.argv[1:]
    with open(source, "rb") as source_file:
        if os.fstat(source_file.fileno()).st_size != SOURCE_SIZE:
            fail("wrong source size")
        text = source_file.read(SOURCE_SIZE + 1)
        if len(text) != SOURCE_SIZE or source_file.read(1):
            fail("wrong source size")
    if hashlib.sha256(text).hexdigest() != SOURCE_SHA256:
        fail("wrong source hash")
    generate(text, output)


if __name__ == "__main__":
    main()
